### ISSUE TITLE
Alignment  when 'C'  in misa CSR is cleared by software

### ISSUE THREAD

**Issue by liweiwei90** [riscv/riscv-isa-sim#1172]
Whether jump to 0x10082 triggers misaligned exception when  'C' in misa CSR is disabled by software? 
The answer is yes before Zc* is supported. 
However,  Zca is implied by 'C', but Zca can work alone without 'C' enabled.  So this becomes a new problem:
Whether Zca is also disabled when 'C' is disabled?

**Comment by aswaterman** [comment]
The spec says the `misa` write is suppressed if the next instruction would not be IALIGN-bit aligned, so we have a few options here:

- Declare that if the implementation supports Zca, then it is unconditionally enabled.  The effect is that IALIGN is always 16 if Zca is supported, regardless of the setting of `misa.C`.  Therefore, clearing `misa.C` will always succeed, regardless of the PC.
- Declare that if the implementation supports C, then disabling C also disables Zca.  In this case, writes to `misa.C` should continue to be suppressed if the PC is not IALIGN-bit aligned.
- Change `misa.C` to be read-only, thereby avoiding this issue.

My preference is the middle option: if the implementation supports C, then clearing `misa.C` should disable Zca.  I think this follows the principle of least surprise.  But the other options are viable.

(Of course, if the implementation supports Zca but does not support C, then this issue is moot: the implementation always has IALIGN=16, because we have no means to disable Zca.)

**Comment by liweiwei90** [comment]
I also prefer the middle. However, there is another question: Whether Zcb/Zcmp/Zcmt will be disabled in the case?

**Comment by aswaterman** [comment]
If Zcmp/Zcmt is implemented, `misa.C` must be hardwired to 0, so that is irrelevant.

Zcb requires Zca, so if we choose a strategy where clearing `misa.C` disables Zca, then clearing `misa.C` must also disable Zcb.

**Comment by aswaterman** [comment]
Zcmp/Zcmt/Zcb require Zca, so if we choose a strategy where clearing `misa.C` disables Zca, then clearing `misa.C` must also disable Zcmp/Zcmt/Zcb.

**Comment by fanghuaqi** [comment]
Hi @liweiwei90 @aswaterman ，if this isa string is `rv32ima_zca_zcb_zcmp_zcmt/rv32imaf_zca_zcb_zcf_zcmp_zcmt/rv32imafd_zca_zcb_zcf_zcmp_zcmt/rv32imafd_zca_zcb_zcf_zcd` , will the `C` bit be set in misa csr? What is current spike implementation do?

From this comment here https://github.com/riscv/riscv-code-size-reduction/issues/144#issuecomment-1034370915

I think misa.c set state should be as below, correct me if I am wrong.

- rv32ima_zca_zcb_zcmp_zcmt: misa.c set 
- rv32imaf_zca_zcb_zcf_zcmp_zcmt: misa.c set
- rv32imafd_zca_zcb_zcf_zcmp_zcmt: misa.c not set
- rv32imafd_zca_zcb_zcf_zcd: misa.c set
- rv32ima_zca: misa.c set

**Comment by fanghuaqi** [comment]
Hi @tariqkurd-repo , do you have any idea on this question https://github.com/riscv-software-src/riscv-isa-sim/issues/1172#issuecomment-1751667541 , which will affect Zc and C reflection on the CSR misa.C bit.
