### ISSUE TITLE
Why the whole-register moves instruction needs to check vill？

### ISSUE THREAD

**Issue by Liuziying04** [riscv/riscv-isa-sim#1378]
The Spec description whole-register moves instruction does not depend on the vtype register and does not need to check vill. But Spike checked vill, what is the reason for this?
![iv9uf4m7nT](https://github.com/riscv-software-src/riscv-isa-sim/assets/127939841/1ffb937d-0eec-4f6e-8af8-379e35041335)

**Comment by aswaterman** [comment]
The whole-register moves _do_ depend on vtype, as their vstart handling is a function of SEW.  As the spec says, "The instructions operate as if EEW=SEW".

The note you quoted in the spec is non-normative, and it was deleted recently because it is incorrect.  https://github.com/riscv/riscv-v-spec/commit/856fe5bd1cb135c39258e6ca941bf234ae63e1b1
