### ISSUE TITLE
Why does spike install libfdt.so at build time?

### ISSUE THREAD

**Issue by unlsycn** [riscv/riscv-isa-sim#1533]
I'm creating a Gentoo ebuild script for spike. And I noticed that spike depends on dtc but at the same time installs libfdt.so, which causes a file collision with dtc. I fixed it simply by substituting $(lib)/spike for install_libs_dir, but I'm still wondering what the difference is between libfdt.so installed by spike and dtc.

**Comment by aswaterman** [comment]
cc @jerryz123, who flipped that switch earlier this year.

**Comment by jerryz123** [comment]
I thought I flipped the switch to enable construction of external "device plugin libraries", which may need to link against libfdt. I didn't realize that libfdt may be already present on the system from the dtc package.

Now that I'm looking at this more thoroughly, it seems like Spike's fdt code is copied from OpenSBI's, which presumably is copied from the upstream dtc project. This PR: https://github.com/riscv-software-src/riscv-isa-sim/pull/455 pulled the fdt into spike.

It seems Spike should just link against a system libfdt, instead of rebuilding its own.

**Comment by aswaterman** [comment]
Unfortunately, libfdt isn't installed on many systems that have dtc, so that change would cause some churn.

My preference would be to avoid making Spike have a new dependence (i.e. continue building libfdt as part of building spike), but stop installing libfdt.so.  For the less-common case that external device plugin libraries need to link against libfdt, can we make only those libraries depend on system libfdt.  Reasonable?

**Comment by jerryz123** [comment]
> Unfortunately, libfdt isn't installed on many systems that have dtc, so that change would cause some churn.

Are these systems unable to acquire libfdt easily through a package manager? If it's such an issue, then your suggestion seems reasonable to me.

**Comment by aswaterman** [comment]
Well, I know it's going to annoy SiFive IT ;)

**Comment by jerryz123** [comment]
Ah, its already annoying me. The latest version in ubuntu 20.04 contains a header file bug that breaks compiles.
Let's just remove the spike-installed libfdt then.

**Comment by aswaterman** [comment]
APIs... what are they even for?
