### ISSUE TITLE
Should sc.d succeed if there is a breakpoint exception between lr.d and sc.d?

### ISSUE THREAD

**Issue by zhangkanqi** [riscv/riscv-isa-sim#1543]
Hi,

I constructed a instruction sequence begins with lr.d and ends with sc.d, there is a breakpoint exception between them. In addition, I have modifed reservation set size to one cache line. **But sc.d fails in spike while succeeds in Boom**.

![image](https://github.com/riscv-software-src/riscv-isa-sim/assets/34207592/5fa16446-4d4a-4bbc-95b3-d4c282a143f4)

I wonder if sc.d should succeed? Besides, i find that sc.d fails in spike because there is a switch between core 0 and core 0, which makes the reservation set released. Should spike add a judgment that if there is only one core, don't release reservation set?

Looking forward to your reply:) Thanks a lot.

**Comment by aswaterman** [comment]
Either behavior is valid.

The ISA says the SC is allowed to fail spuriously, provided forward progress is eventually made.  Per the definition of LR/SC forward progress, taking a trap is considered to be forward progress.  (See https://github.com/riscv/riscv-isa-manual/blob/86b685a624110cf717f75cfaf5afb412b69f7f4e/src/a-st-ext.adoc#L308).  If the trap keeps occurring, then the hart is considered to be progressing, even if the SC never succeeds.

However, there is no requirement that the reservation be yielded on a trap, so it also would have been valid to make the SC succeed.

Since Spike is doing something valid, we will leave it as-is.
