### ISSUE TITLE
FENCE.TSO with invalid opcode

### ISSUE THREAD

**Issue by ajayvreddy** [riscv/riscv-isa-sim#1629]
Hi, 
Spec mentions that In chapter 2.7, `The FENCE.TSO instruction is encoded as a FENCE instruction with fm=1000, predecessor=RW, and successor=RW`

What would be the behavior when predecessor !=RW or successor != RW? 

Should it take an illegal exception or simply ignore? 

Spike seems to be not taking an exception currently.
```
core   0: 0xffff9cc67e40922e (0x88b4040f) fence   i,irw
core   0: 1 0xffff9cc67e40922e (0x88b4040f)
```

**Comment by aswaterman** [comment]
As the spec says, "Base implementations shall treat all such reserved configurations as normal fences with _fm_=0000, and standard software shall use only non-reserved configurations."

So the logic is basically: if `fm`=1000, `pred`=RW, `succ`=RW, then perform the FENCE.TSO operation.  Otherwise, ignore `fm` and execute whatever base FENCE is implied by `pred`/`succ`.
