### ISSUE TITLE
Bug Fix Suggestion for v1.1.0

### ISSUE THREAD

**Issue by zaki-29871** [riscv/riscv-isa-sim#1774]
## Bug Fix
add `#include <cstdint>` at `riscv-isa-sim/fesvr/device.h`.

## Suggestion of Managing Project
Your team could use CMake to build your project. It makes it easier for other users to build and install.

**Comment by aswaterman** [comment]
The missing `#include` was added in 0a7bb5403d0290cea8b2356179d92e4c61ffd51d.  I suggest building from the HEAD of master.

Yes, it is probably time to create a new numbered release of Spike, since there have been many bug fixes and new features since 1.1.0.

I don't think we'll be adopting CMake, but it is always good to hear this kind of feedback.
