### ISSUE TITLE
Setting VL (when rs1 = x0) problem

### ISSUE THREAD

**Issue by panda1628** [riscv/riscv-isa-sim#1875]
VLEN = 128, SEW = 16 and LMUL = 1/8

VLMAX = 1/8 *128/16 = 1
rs1 = x0 and rd != x0 => AVL = ~0 = -1 

According to section 6.1 AVL encoding, 
Set VL to VLMAX = 1

Spike log:
#210 core   0: 0x0000000080800160 (0x00d07357) vsetvli t1, zero, e16, mf8, tu, mu
        3 0x0000000080800160 (0x00d07357) x6  0x0000000000000000

However, Spike set VL to 0x0.

Do I miss anything?

**Comment by aswaterman** [comment]
It's because you asked for an illegal configuration, and so `vtype.vill` got set to 1, and so `vl` got set to 0.

As the spec says, "For a given supported fractional LMUL setting, implementations must support SEW settings between SEWMIN and LMUL * ELEN".  Here, you are selecting SEW=16, which is out of the range [8, (1/8 * 64)].

So, there's no bug.
