### ISSUE TITLE
Bad isa option 'rv64gch' 

### ISSUE THREAD

**Issue by Vasanvs** [riscv/riscv-isa-sim#805]
In the latest Spike commit version, if we try to invoke spike as follows:

spike --isa rv64gch <ELF payload file path>

We get an error message reported back as below before exiting:

error: bad --isa option 'rv64gch'. unsupported extension: h

Has the Hypervisor H extension changed during the last checkin for naming convention?

**Comment by aswaterman** [comment]
@marcfedorow your #802 has broken this.  Please accept 'h' as a means to enable the hypervisor extension.

**Comment by aswaterman** [comment]
@Vasanvs @neelgala in the mean time, please discard the most recent commit on master.

**Comment by aswaterman** [comment]
@marcfedorow I've fixed it myself.  The issue is that you were taking the spec literally, that H is a prefix rather than an extension name.  Unfortunately, the spec is out of date in this regard.  'S' will be used as a prefix for all privileged extensions going forward.  (In fact, that chapter needs to be completely rewritten...)
