### ISSUE TITLE
vxsat CSR doesn't work with P-ext

### ISSUE THREAD

**Issue by marcfedorow** [riscv/riscv-isa-sim#823]
`vxsat` requires V-ext enabled. Also it sets some vector states.
Thus kadd16 is illegal if -march=rv64imp.
@scottj97

**Comment by scottj97** [comment]
I was unaware that `kadd16` and friends share some state (vxsat) with the vector extension.

I can see that my commit 347ff31125bee0fadd8e02bbe7a13c672dcf74a5 inadvertently changed the behavior of `kadd16` to ~~take an exception if misa.V=0~~ [edit: no it didn't]. But I'm not sure that Spike was ever fully correct here. Reading through the P spec, it seems that `csrrw vxsat` is supported? I can't see that in Spike -- it was always requiring the V extension for that CSR access. Should that be (V || P)?

Second, if -march=rv64gmpv, what should happen to mstatus.VS when `kadd16` modifies `vxsat`? It seems to me that it should set it to Dirty, yes? I don't believe it was doing so prior to 347ff31125bee0fadd8e02bbe7a13c672dcf74a5.

# Proposed change

1. Create `vxsat` CSR and allow access to it via `csrrw` if either misa.V or misa.P are set. (Today it requires misa.V.)

2. When `vxsat` is modified by any instruction, set `mstatus.VS=Dirty` iff misa.V==1. (Today it sets `mstatus.VS=Dirty` ~~unconditionally~~ only if misa.V==1. Prior to 347ff31125bee0fadd8e02bbe7a13c672dcf74a5 it was only setting it for Vector instructions, not P instructions.)

Does this sound like the correct behavior? I'm not that familiar with either P or V specs.

**Comment by aswaterman** [comment]
I think you left out point # 3; maybe you were already thinking this implicitly:

`vxsat` should be inaccessible (by `csrrw` or by a P or V instruction) when `misa.V`=1 and `mstatus.VS`=Off.  In other words, if V is present, P instructions must respect `VS`.

**Comment by scottj97** [comment]
cc @chuanhua not sure how this is intended to work

**Comment by aswaterman** [comment]
The vector spec already clears up most of the questions.  It says that _any_ instruction that accesses vector state (including `vxsat`) is controlled by `VS`.

Then the only question is, when is the `VS` field present?  The P extension makes no mention of it, so we can conclude that VS only exists if the V extension is present.  So, P instructions that access `vxsat` should be gated on `misa.V == 0 || mstatus.VS != Off`, and P instructions that write `vxsat` should set `VS` to Dirty if that gating function is satisfied.

**Comment by scottj97** [comment]
> So, P instructions that access `vxsat` should be gated on `misa.V == 0 || mstatus.VS != Off`, and P instructions that write `vxsat` should set `VS` to Dirty if that gating function is satisfied.

That doesn't sound quite right...the V spec says:

> Implementations may have a writable misa.V field. Analogous to the way in which the floating-point unit is handled, the
mstatus.VS field may exist even if misa.V is clear.

So that would mean that we would write mstatus.VS=Dirty even when misa.V==0? (But only if V is in the ISA string?) Is that okay?

Upon further research, I see that Spike does not have a writable misa.V field. So VS doesn't exist in that case.

I am tempted to simply revert my inadvertent change and let others more familiar with with P&V specs deal with these other issues.

**Comment by aswaterman** [comment]
I forgot about that clause.  What I wrote is one valid implementation: as the sentence you quoted says, VS _may_ exist when misa.V is cleared, but it isn't required to exist.  I think that keeping VS around will be a more common implementation strategy, though, so it would be pragmatic to do what you suggested.

I suggest you not revert the change and instead do what you've just suggested: condition P instructions that access `vxsat` on `VS` if V is in the ISA string, and set `VS` to Dirty on P instructions that write `vxsat` if V is in the ISA string.  You can use `misa.V` as a proxy since, as you pointed out, it's not mutable.

**Comment by scottj97** [comment]
More research: I cannot see the problem @marcfedorow alluded to. I can successfully run kadd16 even with --isa=rv64imcp (i.e., without V). The commit log shows the write to vxsat, and an extra write to mstatus from it trying (unsuccessfully) to set VS.

The only observable difference I can find from my recent changes is that P-instructions writing vxsat now set mstatus.VS=Dirty when misa.V=1, which is a desirable if unintended change.

Marc, can you explain the expected behavior vs the observed behavior? I am unable to find anything that I broke here.

**Comment by aswaterman** [comment]
@scottj97 And do P instructions that access `vxsat` check whether VS=Off then trap when misa.V=1?  That seems like the only missing thing from what you've just described.

**Comment by scottj97** [comment]
> @scottj97 And do P instructions that access `vxsat` check whether VS=Off then trap when misa.V=1?

No they do not...nor is vxsat accessible via `csrrw` when misa.V==0. But neither of those things have changed recently.

**Comment by kito-cheng** [comment]
misa.V is 0 when zve* extension is enabled, so I think misa.V can't be the condition checking of vxsat?

**Comment by aswaterman** [comment]
Yes, it should be more precise: “does VS exist”.

**Comment by marcfedorow** [comment]
> I can successfully run kadd16 even with --isa=rv64imcp (i.e., without V)

kadd16.h says:
https://github.com/riscv-software-src/riscv-isa-sim/blob/bcab7c19ed4cf997f6c55587b0481f32b3a612f4/riscv/insns/kadd16.h#L4
which is
https://github.com/riscv-software-src/riscv-isa-sim/blob/bcab7c19ed4cf997f6c55587b0481f32b3a612f4/riscv/decode.h#L2346
We know that vxsat is vector_csr_t via
https://github.com/riscv-software-src/riscv-isa-sim/blob/bcab7c19ed4cf997f6c55587b0481f32b3a612f4/riscv/processor.cc#L548
and we know that vxsat requires V-ext enabled
https://github.com/riscv-software-src/riscv-isa-sim/blob/bcab7c19ed4cf997f6c55587b0481f32b3a612f4/riscv/csrs.cc#L1198-L1203

I do not know why @scottj97 can not reproduce my error.

**Comment by marcfedorow** [comment]
Also I think it is incorrect that P_SET_OV macro writes to vxsat even if it should not.
Macro should be something like
```
if (ov) P.VU.vxsat->write(P.VU.vxsat->read());
```
to be consistent with spec.

**Comment by scottj97** [comment]
> I do not know why @scottj97 can not reproduce my error.

It is not clear to me what error you are seeing. I will guess it is:

Expected behavior: with --isa=rv64imp, `kadd16` should execute without any exceptions

Actual behavior: with --isa=rv64imp, `kadd16` takes an illegal instruction exception

Is that correct?

Is the misbehavior you observe something new? Did older versions of Spike work correctly?

I have observed that (at least in my testcase) `kadd16` executes successfully. If you are seeing something different, then there is more to the problem that we apparently don't understand. It is not the lack of V in the --isa that is causing the exception you observe.

Method `verify_permissions()` is called by `csrrw` and friends. It is not called by `read()` or `write()`. That's why `kadd16` doesn't take any exception when it reads and writes `vxsat`.

**Comment by scottj97** [comment]
> ```
> if (ov) P.VU.vxsat->write(P.VU.vxsat->read());
> ```

That would have no effect. I assume you meant:
```
if (ov) P.VU.vxsat->write(1);
```

As opposed to the current code: https://github.com/riscv-software-src/riscv-isa-sim/blob/bcab7c19ed4cf997f6c55587b0481f32b3a612f4/riscv/decode.h#L2345-L2346

~~But I see no functional difference between those two.~~ The only difference would be in the commit log -- no trace event for `vxsat` would be seen unless it's being set. [Edit: it would also no longer set mstatus.VS=Dirty.]

**Comment by marcfedorow** [comment]
> Expected behavior: with --isa=rv64imp, `kadd16` should execute without any exceptions
> 
> Actual behavior: with --isa=rv64imp, `kadd16` takes an illegal instruction exception

~~Yes, this is correct~~
I made some additional research. It seems like I misinterpreted spike's trace. The actual problem is:

**Expected behavior: with --isa=rv64imp, `clrov` should execute without any exceptions
Actual behavior: with --isa=rv64imp, `clrov` takes an illegal instruction exception**

Still there is a question -- does `clrov` really require 'v'-extension?
It is described in riscv-p-spec so it probably also should work with `rv32imcp` (i.e. without `v`).

> Did older versions of Spike work correctly?

No, but it is harder to make a quickfix when `vxsat` became `vector_csr_t`.

>  I assume you meant:
> 
> ```
> if (ov) P.VU.vxsat->write(1);
> ```

Yes, this is exactly what I meant. Thank you for the fix.

> The only difference would be in the commit log

Yes, I think that `vxsat` event should not be logged if insn does not set `OV` flag.

**Comment by scottj97** [comment]
OK, I think I understand now. The problem was not caused by my recent CSR refactoring (whew!) but has been there since the P-spec was [first added](https://github.com/riscv-software-src/riscv-isa-sim/pull/637), it seems.

I will put together a PR to attempt to fix.

**Comment by scottj97** [comment]
> Yes, I think that `vxsat` event should not be logged if insn does not set `OV` flag.

I was mistaken; there is a functional difference here. If mstatus.VS exists, it will not be dirtied anymore, unless the instruction is setting `vxsat=1`.

I would call this an improvement.

**Comment by chuanhua** [comment]
Sharing `vxsat` CSR between V and P seems to create a lot of confusion on the `misa.V` and `mstatus.VS` states. I think it is cleaner to have a separate overflow flag CSR that has its presence conditioned on the `misa.P==1` state. And this will also allow the P and V instructions to be mixed in a program without worrying about thrashing each other's saturation state.

**Comment by aswaterman** [comment]
I realize sharing `vxsat` between P and V creates confusion, and that we need to be careful in specifying the interaction, but it is a technically superior choice that @kasanovic, @jhauser-us, and I have discussed a few times over.  Rationale is:
- It reduces context-switch cost.
- It's generally better for performance to use the same flag.  What you describe as thrashing is actually beneficial: software only needs to check one register to determine if saturation occurred anywhere in the computation.  This is especially important in the case of auto-vectorization, since the programmer has no idea whether the code will be vectorized using P or V.  When the code is in a different translation unit, the compiler doesn't know, either.  And so, if the saturation flags were separate, the programmer (or the compiler) would usually need to read two CSRs and OR them together.

We followed the same rationale in combining `fflags` for the F and V extensions.  Similar confusion resulted from that decision, too, but it's worth the effort.
